### ISSUE TITLE
Incorrect local variable matching

### ISSUE THREAD

**Issue by k-badz** [rizinorg/rizin#3333]
**Environment information**
* Operating System: FLARE-VM
* Cutter version: 2.1.2
* Obtained from: FLARE-VM
* File format:

**Describe the bug**

In screenshots below, Cutter didn't match local variables correctly (**lpFilename** and **var_60h_2**), both of them have the same state of ESP, and are the same instructions. Their memory operand is [esp+60h].

You can see that Cutter assigned different stack offset for these (difference of 0xC). It looks like it didn't properly recognized GetModuleFileNameW calling convention and assumed that ESP should be cleaned by caller.

**To Reproduce**

1. Open https://github.com/HuskyHacks/PMAT-labs/blob/main/labs/2-1.AdvancedStaticAnalysis/Dropper.DownloadFromURL.exe.malz/Dropper.DownloadFromURL.exe.7z/<exe inside>
2. Navigate to "main" function.
3. Check the offsets from screenshots.

**Expected behavior**

**lpFilename** and **var_60h_2** should be considered the same local variable.

Both IDA Free and Ghidra do that properly.

**Screenshots**

Cutter:
![image](https://user-images.githubusercontent.com/101342783/211424032-366afc41-587b-47f8-ab80-7a32775f45d1.png)
![image](https://user-images.githubusercontent.com/101342783/211425627-a5bd6246-be85-4d04-9534-cc41913cd95f.png)

Ghidra:
![image](https://user-images.githubusercontent.com/101342783/211425265-1079f2c2-e677-4794-bd33-d8643e0f1846.png)

IDA Free:
![image](https://user-images.githubusercontent.com/101342783/211425461-fbe27e8d-4be0-4c3f-87bb-9d01c55f24ce.png)

**Comment by XVilka** [comment]
It should be fixed already in the latest `dev` branch. Could you please try it?

**Comment by k-badz** [comment]
@XVilka  Just took latest dev, rebuilt it and it seems to still be there:
![image](https://user-images.githubusercontent.com/101342783/211528835-de2aa0cc-72df-42fd-977b-73839753629e.png)
![image](https://user-images.githubusercontent.com/101342783/211528780-ed84299c-0364-48ae-81fe-cfe47619380f.png)

**Comment by k-badz** [comment]
@XVilka hello, just FYI - I took latest Cutter 2.2.0 release to check stack analysis fixes:
![image](https://user-images.githubusercontent.com/101342783/223243190-e8f96bc6-5cec-4c18-956f-4a8331708595.png)

Unfortunately, it seems issue is still there (12 bytes offset from 3 parameters being pushed to stack, like it didn't recognize proper stdcall calling convention):
![image](https://user-images.githubusercontent.com/101342783/223243608-550b4f96-a7b5-42d4-a2f5-bb67cb330ec1.png)
![image](https://user-images.githubusercontent.com/101342783/223243649-95144533-9a69-4488-8c71-f26bc1933544.png)

**Comment by ret2libc** [comment]
I think I discussed this with @thestr4ng3r already. We should consider the calling convention and perform the stack analysis in the calling order.

**Comment by k-badz** [comment]
Maybe it works only for statically linked functions as of now? I saw that you can manually change the convention for these, but dynamically linked stubs might not be properly recognized as functions. (?)

**Comment by notxvilka** [comment]
It is better to do once the RzIL-based analysis is landed.
